# Common Bangla words with English translations
# Used as fallback when API quota is exhausted

COMMON_WORDS = {
    # Pronouns
    "আমি": "I",
    "তুমি": "you",
    "সে": "he/she",
    "আমরা": "we",
    "তারা": "they",
    "এটা": "this",
    "ওটা": "that",
    "কি": "what",
    "কে": "who",
    "কেন": "why",
    "কোথায়": "where",
    "কখন": "when",
    "কিভাবে": "how",

    # Common verbs
    "করা": "to do",
    "করে": "does",
    "করছে": "is doing",
    "করেছে": "has done",
    "হয়": "happens/is",
    "হচ্ছে": "is happening",
    "হয়েছে": "has happened",
    "যায়": "goes",
    "আসে": "comes",
    "বলে": "says",
    "বলছে": "is saying",
    "দেখা": "to see",
    "দেখে": "sees",
    "জানা": "to know",
    "জানে": "knows",
    "চায়": "wants",
    "পারে": "can",
    "থাকে": "stays/lives",
    "দেয়": "gives",
    "নেয়": "takes",
    "রাখে": "keeps",
    "পায়": "gets",
    "খায়": "eats",
    "পড়ে": "reads/falls",
    "লেখে": "writes",
    "শোনে": "hears",
    "বোঝে": "understands",
    "ভাবে": "thinks",
    "মনে": "in mind",

    # Common nouns
    "মানুষ": "person/people",
    "লোক": "people",
    "দেশ": "country",
    "বাংলাদেশ": "Bangladesh",
    "ঢাকা": "Dhaka",
    "সরকার": "government",
    "কাজ": "work",
    "সময়": "time",
    "দিন": "day",
    "রাত": "night",
    "বছর": "year",
    "মাস": "month",
    "ঘণ্টা": "hour",
    "টাকা": "money/taka",
    "পানি": "water",
    "খাবার": "food",
    "ঘর": "house/room",
    "বাড়ি": "home",
    "রাস্তা": "road",
    "গাড়ি": "car",
    "স্কুল": "school",
    "শিক্ষা": "education",
    "বিশ্ববিদ্যালয়": "university",
    "হাসপাতাল": "hospital",
    "ডাক্তার": "doctor",
    "পুলিশ": "police",
    "সংবাদ": "news",
    "খবর": "news",
    "কথা": "words/talk",
    "প্রশ্ন": "question",
    "উত্তর": "answer",
    "সমস্যা": "problem",
    "সমাধান": "solution",
    "পরিবার": "family",
    "বন্ধু": "friend",
    "ছেলে": "boy/son",
    "মেয়ে": "girl/daughter",
    "বাবা": "father",
    "মা": "mother",
    "ভাই": "brother",
    "বোন": "sister",

    # Adjectives
    "ভালো": "good",
    "খারাপ": "bad",
    "বড়": "big",
    "ছোট": "small",
    "নতুন": "new",
    "পুরানো": "old",
    "সুন্দর": "beautiful",
    "কঠিন": "hard/difficult",
    "সহজ": "easy",
    "দ্রুত": "fast",
    "ধীর": "slow",
    "গরম": "hot",
    "ঠান্ডা": "cold",
    "বেশি": "more/much",
    "কম": "less/few",
    "সব": "all",
    "কিছু": "some",
    "অনেক": "many/much",
    "প্রথম": "first",
    "শেষ": "last",

    # Time words
    "আজ": "today",
    "কাল": "yesterday/tomorrow",
    "এখন": "now",
    "তখন": "then",
    "আগে": "before",
    "পরে": "after",
    "সকাল": "morning",
    "দুপুর": "noon",
    "বিকাল": "afternoon",
    "সন্ধ্যা": "evening",

    # Prepositions/postpositions
    "থেকে": "from",
    "পর্যন্ত": "until",
    "জন্য": "for",
    "সাথে": "with",
    "মধ্যে": "among/in",
    "উপর": "on/above",
    "নিচে": "below",
    "ভিতরে": "inside",
    "বাইরে": "outside",

    # Conjunctions
    "এবং": "and",
    "কিন্তু": "but",
    "অথবা": "or",
    "যদি": "if",
    "তাহলে": "then",
    "কারণ": "because",
    "যখন": "when",
    "যেখানে": "where",

    # Numbers
    "এক": "one",
    "দুই": "two",
    "তিন": "three",
    "চার": "four",
    "পাঁচ": "five",
    "ছয়": "six",
    "সাত": "seven",
    "আট": "eight",
    "নয়": "nine",
    "দশ": "ten",
    "শত": "hundred",
    "হাজার": "thousand",
    "লাখ": "hundred thousand",
    "কোটি": "ten million",

    # Common phrases/words from news
    "প্রধানমন্ত্রী": "prime minister",
    "রাষ্ট্রপতি": "president",
    "মন্ত্রী": "minister",
    "নির্বাচন": "election",
    "সংসদ": "parliament",
    "আদালত": "court",
    "বিচার": "justice/trial",
    "আইন": "law",
    "অর্থনীতি": "economy",
    "ব্যবসা": "business",
    "শিল্প": "industry",
    "কৃষি": "agriculture",
    "পরিবেশ": "environment",
    "দূষণ": "pollution",
    "বায়ু": "air",
    "জলবায়ু": "climate",
    "স্বাস্থ্য": "health",
    "রোগ": "disease",
    "চিকিৎসা": "treatment",
    "ওষুধ": "medicine",
    "ক্রিকেট": "cricket",
    "খেলা": "game/sport",
    "জয়": "victory",
    "হার": "defeat",

    # Common inflected forms
    "ঢাকায়": "in Dhaka",
    "বাংলাদেশে": "in Bangladesh",
    "দেশে": "in the country",
    "বাড়িতে": "at home",
    "সময়ে": "at the time",
    "কাজে": "at work",
    "পথে": "on the way",
    "মতে": "according to",
    "জানান": "informed",
    "বলেন": "said (formal)",
    "করেন": "does (formal)",
    "হবে": "will be",
    "করবে": "will do",
    "যাবে": "will go",
    "আসবে": "will come",
    "রয়েছে": "is/exists",
    "ছিল": "was",
    "হয়েছিল": "had happened",
    "করেছিল": "had done",
}


def get_fallback_translation(word: str) -> str | None:
    """Return translation from fallback dictionary, or None if not found."""
    return COMMON_WORDS.get(word)
